# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_labeler.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_image_labeler(object):
    def setupUi(self, image_labeler):
        image_labeler.setObjectName("image_labeler")
        image_labeler.resize(779, 760)
        self.centralWidget = QtWidgets.QWidget(image_labeler)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 751, 618))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainGraphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.mainGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mainGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mainGraphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.mainGraphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.mainGraphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.mainGraphicsView.setObjectName("mainGraphicsView")
        self.verticalLayout_3.addWidget(self.mainGraphicsView)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_eggs = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_eggs.setObjectName("pushButton_eggs")
        self.gridLayout_2.addWidget(self.pushButton_eggs, 1, 1, 1, 1)
        self.pushButton_worm_hard = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_worm_hard.setCheckable(True)
        self.pushButton_worm_hard.setObjectName("pushButton_worm_hard")
        self.gridLayout_2.addWidget(self.pushButton_worm_hard, 0, 2, 1, 1)
        self.pushButton_aggregate = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_aggregate.setCheckable(True)
        self.pushButton_aggregate.setObjectName("pushButton_aggregate")
        self.gridLayout_2.addWidget(self.pushButton_aggregate, 1, 0, 1, 1)
        self.pushButton_bad = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_bad.setCheckable(True)
        self.pushButton_bad.setObjectName("pushButton_bad")
        self.gridLayout_2.addWidget(self.pushButton_bad, 0, 0, 1, 1)
        self.pushButton_worm = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_worm.setCheckable(True)
        self.pushButton_worm.setObjectName("pushButton_worm")
        self.gridLayout_2.addWidget(self.pushButton_worm, 0, 1, 1, 1)
        self.spinBox_samp_ord = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_samp_ord.setMaximum(999999999)
        self.spinBox_samp_ord.setObjectName("spinBox_samp_ord")
        self.gridLayout_2.addWidget(self.spinBox_samp_ord, 3, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 3, 2, 1, 1)
        self.label_samp_ord = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_samp_ord.setObjectName("label_samp_ord")
        self.gridLayout_2.addWidget(self.label_samp_ord, 3, 0, 1, 1)
        self.pushButton_larvae = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_larvae.setObjectName("pushButton_larvae")
        self.gridLayout_2.addWidget(self.pushButton_larvae, 1, 2, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setText("")
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 2, 0, 1, 1)
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 2, 1, 1, 1)
        self.pushButton_h5groups = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_h5groups.sizePolicy().hasHeightForWidth())
        self.pushButton_h5groups.setSizePolicy(sizePolicy)
        self.pushButton_h5groups.setObjectName("pushButton_h5groups")
        self.gridLayout.addWidget(self.pushButton_h5groups, 0, 1, 1, 1)
        self.comboBox_h5path = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_h5path.setEditable(True)
        self.comboBox_h5path.setObjectName("comboBox_h5path")
        self.comboBox_h5path.addItem("")
        self.comboBox_h5path.addItem("")
        self.gridLayout.addWidget(self.comboBox_h5path, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        image_labeler.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(image_labeler)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 779, 22))
        self.menuBar.setObjectName("menuBar")
        image_labeler.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(image_labeler)
        self.mainToolBar.setObjectName("mainToolBar")
        image_labeler.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.toolBar = QtWidgets.QToolBar(image_labeler)
        self.toolBar.setObjectName("toolBar")
        image_labeler.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(image_labeler)
        QtCore.QMetaObject.connectSlotsByName(image_labeler)

    def retranslateUi(self, image_labeler):
        _translate = QtCore.QCoreApplication.translate
        image_labeler.setWindowTitle(_translate("image_labeler", "TrackerViewerAux"))
        self.pushButton_eggs.setText(_translate("image_labeler", "Eggs"))
        self.pushButton_worm_hard.setText(_translate("image_labeler", "Difficult worm"))
        self.pushButton_aggregate.setText(_translate("image_labeler", "Worms aggregate"))
        self.pushButton_bad.setText(_translate("image_labeler", "Not a worm"))
        self.pushButton_worm.setText(_translate("image_labeler", "Valid worm"))
        self.checkBox.setText(_translate("image_labeler", "show skeleton"))
        self.label_samp_ord.setText(_translate("image_labeler", "sample number"))
        self.pushButton_larvae.setText(_translate("image_labeler", "Lavae"))
        self.pushButton_save.setText(_translate("image_labeler", "SAVE"))
        self.pushButton_video.setText(_translate("image_labeler", "Select Video File"))
        self.pushButton_h5groups.setText(_translate("image_labeler", "Update Groups"))
        self.comboBox_h5path.setItemText(0, _translate("image_labeler", "/mask"))
        self.comboBox_h5path.setItemText(1, _translate("image_labeler", "/full_data"))
        self.toolBar.setWindowTitle(_translate("image_labeler", "toolBar"))

